POST http://localhost:5000/api/users
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzIwMDc2NjE1LCJleHAiOjE3MjA2ODE0MTV9.G5nI7Cf2uzcXc7iYdpxSKASmGr2hG6fPGV6QoGOtS3A

{
    "name": "zul",
    "email": "admin@mail.com",
    "password": "123456",
    "confPassword": "123456",
    "role": "Admin"
}

###
PATCH  http://localhost:5000/api/users/9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzE5OTk2OTAzLCJleHAiOjE3MjA2MDE3MDN9.RYcZ9xoSJxhaAdNNCfX_sjb2SFPHvNMOCvgattFNDa4

{
    "name": "zul",
    "email": "zul@mail.com",
    "password": "123456",
    "role": "Admin"
}

###
POST http://localhost:5000/api/login
Content-Type: application/json

{
  "email": "admin@mail.com",
  "password": "123456"
}

###
PUT   http://localhost:5000/api/other/updateKadaluarsa
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzIwNzczMDk3LCJleHAiOjE3MjEzNzc4OTd9.fcbhxkRRBA6Zx12peEWtU2xedZjCRVPEJ9VS4tCLpJc

###
GET  http://localhost:5000/api/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6ImFwb3Rla2VyIiwiaWF0IjoxNzE5ODE4MjMyLCJleHAiOjE3MjA0MjMwMzJ9.5SEZ0Pr9mNa65SRXCJ0nrPsyqcU7KqTRxwmLJQ_tGK4

###
GET  http://localhost:5000/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzE5OTk2OTAzLCJleHAiOjE3MjA2MDE3MDN9.RYcZ9xoSJxhaAdNNCfX_sjb2SFPHvNMOCvgattFNDa4

###
GET  http://localhost:5000/api/users/9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzE5OTk2OTAzLCJleHAiOjE3MjA2MDE3MDN9.RYcZ9xoSJxhaAdNNCfX_sjb2SFPHvNMOCvgattFNDa4


###
DELETE   http://localhost:5000/api/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6IkFwb3Rla2VyIiwiaWF0IjoxNzE5OTk2ODYxLCJleHAiOjE3MjA2MDE2NjF9.t2WaJRKZ2V5bO34pdeVuRX2gIe7jsdVpB4zmr-twoQY

###
GET  http://localhost:5000/kategori
Content-Type: application/json

###
GET  http://localhost:5000/kategori/12
Content-Type: application/json

###
POST http://localhost:5000/kategori
Content-Type: application/json

{
    "nama": "Obat Pencahar"
}

###
PATCH  http://localhost:5000/kategori/16
Content-Type: application/json

{
    "nama": "Antibiotik"
}

###
DELETE   http://localhost:5000/kategori/15
Content-Type: application/json


###
GET  http://localhost:5000/api/obat
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzIwNTc1Nzg2LCJleHAiOjE3MjExODA1ODZ9.x85Y5ZskiwzLL5nJtnj4tfXUH76RfsGL0SIgL1sGbgA

###
GET  http://localhost:5000/api/obat?start_date=2024-07-01&end_date=2024-07-07
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzIwNTc1Nzg2LCJleHAiOjE3MjExODA1ODZ9.x85Y5ZskiwzLL5nJtnj4tfXUH76RfsGL0SIgL1sGbgA

###
GET  http://localhost:5000/obat/3
Content-Type: application/json

###
POST http://localhost:5000/obat
Content-Type: application/json

{
    "nama_obat": "Antikolinergik",
    "stok": 7,
    "harga": 15000,
    "tanggal_kadaluarsa": "2024-05-10",
    "id_kategori": 8
}

###
PATCH  http://localhost:5000/obat/3
Content-Type: application/json

{
    "nama_obat": "Obat Paramex",
    "stok": 5,
    "harga": 3000,
    "tanggal_kadaluarsa": "2024-05-10",
    "id_kategori": 8
}

###
DELETE   http://localhost:5000/obat/5
Content-Type: application/json


###
GET  http://localhost:5000/api/batch
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzIwMTA1MTg5LCJleHAiOjE3MjA3MDk5ODl9.mYc7MgL3ZwGjoEQG94jBFcNXkMmbsn3artx3WKkd4OA

###
GET  http://localhost:5000/batch/7
Content-Type: application/json

###
POST http://localhost:5000/api/batch
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzIwMTA1MTg5LCJleHAiOjE3MjA3MDk5ODl9.mYc7MgL3ZwGjoEQG94jBFcNXkMmbsn3artx3WKkd4OA

{
    "tanggal_produksi": "2024-04-01",
    "id_obat": 6
}

###
DELETE   http://localhost:5001/batch/12
Content-Type: application/json

###
PATCH  http://localhost:5000/api/batch/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzIwMTA1MTg5LCJleHAiOjE3MjA3MDk5ODl9.mYc7MgL3ZwGjoEQG94jBFcNXkMmbsn3artx3WKkd4OA

{
    "tanggal_produksi": "2024-04-03",
    "id_obat": 6
}

###
POST http://localhost:5000/api/penjualan
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzIwMzQwMTI0LCJleHAiOjE3MjA5NDQ5MjR9.3hG9IByrE1hei15ohjQoOGCmhCs3-5WKT7Cq9QFrMPg

{
    "jumlah": 2,
    "tanggal_transaksi": "2024-07-08",
    "id_obat": 6
}

###
GET  http://localhost:5000/api/penjualan/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzIwMTA1MTg5LCJleHAiOjE3MjA3MDk5ODl9.mYc7MgL3ZwGjoEQG94jBFcNXkMmbsn3artx3WKkd4OA

###
DELETE   http://localhost:5000/api/penjualan/23
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzIwMzQwMTI0LCJleHAiOjE3MjA5NDQ5MjR9.3hG9IByrE1hei15ohjQoOGCmhCs3-5WKT7Cq9QFrMPg


###
GET  http://localhost:5000/api/laporan/data
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6IkFkbWluIiwiaWF0IjoxNzIwMTA1MTg5LCJleHAiOjE3MjA3MDk5ODl9.mYc7MgL3ZwGjoEQG94jBFcNXkMmbsn3artx3WKkd4OA