POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "zulfiqor",
    "email": "admin@mail.com",
    "password": "123456",
    "confPassword": "123456",
    "role": "admin"
}

###
POST http://localhost:5001/login
Content-Type: application/json

{
  "email": "admin@mail.com",
  "password": "123456"
}

###
GET  http://localhost:5000/me
Content-Type: application/json

###
GET  http://localhost:5000/users
Content-Type: application/json

###
DELETE   http://localhost:5000/logout
Content-Type: application/json

###
GET  http://localhost:5000/kategori
Content-Type: application/json

###
GET  http://localhost:5000/kategori/12
Content-Type: application/json

###
POST http://localhost:5000/kategori
Content-Type: application/json

{
    "nama": "Obat Pencahar"
}

###
PATCH  http://localhost:5000/kategori/16
Content-Type: application/json

{
    "nama": "Antibiotik"
}

###
DELETE   http://localhost:5000/kategori/15
Content-Type: application/json


###
GET  http://localhost:5001/obat
Content-Type: application/json

###
GET  http://localhost:5001/obat/3
Content-Type: application/json

###
POST http://localhost:5001/obat
Content-Type: application/json

{
    "nama_obat": "Antikolinergik",
    "stok": 7,
    "harga": 15000,
    "tanggal_kadaluarsa": "2024-05-10",
    "id_kategori": 8
}

###
PATCH  http://localhost:5001/obat/3
Content-Type: application/json

{
    "nama_obat": "Obat Paramex",
    "stok": 5,
    "harga": 3000,
    "tanggal_kadaluarsa": "2024-05-10",
    "id_kategori": 8
}

###
DELETE   http://localhost:5001/obat/5
Content-Type: application/json


###
GET  http://localhost:5001/batch
Content-Type: application/json

###
GET  http://localhost:5001/batch/7
Content-Type: application/json

###
POST http://localhost:5001/batch
Content-Type: application/json

{
    "batches": [
        {
            "tanggal_produksi": "2024-07-01",
            "id_obat": 3
        },
        {
            "tanggal_produksi": "2024-04-02",
            "id_obat": 4
        }
    ]
}

###
DELETE   http://localhost:5001/batch/12
Content-Type: application/json